"""add seller_id

Revision ID: 196baff7d3ea
Revises: ac8dfca09ca0
Create Date: 2023-03-09 14:02:30.691510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196baff7d3ea'
down_revision = 'ac8dfca09ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller_id', sa.Integer(),
                                       nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'seller_id')
    # ### end Alembic commands ###
