"""add price & autoincrement id

Revision ID: 523594af7209
Revises: 196baff7d3ea
Create Date: 2023-03-09 21:44:42.383696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523594af7209'
down_revision = '196baff7d3ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    # ### end Alembic commands ###
